In [1]:
# Import necessary libraries
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

%load_ext autoreload
%autoreload 2

# Load test module for sanity check
from test_utils import test

Data Generation
===

In [3]:
num_samples, num_features = 10, 5

In [4]:
np.random.seed(10)
data = np.random.rand(num_samples, num_features)

Solution
===

In [6]:
print(data)

[[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701]
 [0.22479665 0.19806286 0.76053071 0.16911084 0.08833981]
 [0.68535982 0.95339335 0.00394827 0.51219226 0.81262096]
 [0.61252607 0.72175532 0.29187607 0.91777412 0.71457578]
 [0.54254437 0.14217005 0.37334076 0.67413362 0.44183317]
 [0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]
 [0.8052232  0.52164715 0.90864888 0.31923609 0.09045935]
 [0.30070006 0.11398436 0.82868133 0.04689632 0.62628715]
 [0.54758616 0.819287   0.19894754 0.8568503  0.35165264]
 [0.75464769 0.29596171 0.88393648 0.32551164 0.1650159 ]]


In [27]:
def standardize(x):
    """Stadartize the input data x

    Args:
        x: numpy array of shape=(num_samples, num_features)

    Returns:
        standartized data, shape=(num_samples, num_features)

    >>> standardize(np.array([[1, 2], [3, 4], [5, 6]]))
    array([[-1.22474487, -1.22474487],
           [ 0.        ,  0.        ],
           [ 1.22474487,  1.22474487]])
    """

    new_x = x-np.mean(x, axis=0)

    return new_x/np.std(x, axis=0)


test(standardize)

✅ Your `standardize` passed 1 tests.


In [21]:
std_data = standardize(data)
print(std_data, "\n\n", np.mean(std_data, axis=0), "\n\n", np.std(std_data, axis=0))

[[ 0.20344878 -0.41972612  0.09397858  0.22671326  0.05947394]
 [-0.34307522 -0.24241521  0.22086106 -0.35297979 -0.35069326]
 [ 0.11748795  0.51291527 -0.53572138 -0.00989836  0.37358789]
 [ 0.0446542   0.28127725 -0.24779358  0.3956835   0.27554271]
 [-0.0253275  -0.29830802 -0.16632889  0.15204299  0.0028001 ]
 [-0.13385787  0.17728891 -0.02653141  0.12830656  0.16200588]
 [ 0.23735133  0.08116908  0.36897923 -0.20285454 -0.34857372]
 [-0.26717181 -0.32649371  0.28901168 -0.47519431  0.18725407]
 [-0.02028571  0.37880892 -0.34072211  0.33475968 -0.08738043]
 [ 0.18677583 -0.14451637  0.34426683 -0.19657899 -0.27401718]] 

 [-3.33066907e-17  2.22044605e-17 -1.11022302e-17  0.00000000e+00
  6.66133815e-17] 

 [0.18880201 0.31226926 0.29810476 0.28105224 0.24648668]
